//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Careers.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ejecutivos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ejecutivos()
        {
            this.Horarios = new HashSet<Horarios>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public int EmpresaId { get; set; }
        public int NivelOrganizacionalId { get; set; }
        public int ApoyoId { get; set; }
        public int CanalId { get; set; }
    
        public virtual Canal Canal { get; set; }
        public virtual Colaborador Colaborador { get; set; }
        public virtual Empresa Empresa { get; set; }
        public virtual NivelOrganizacional NivelOrganizacional { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Horarios> Horarios { get; set; }
    }
}
