//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Careers.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Horarios
    {
        public int Id { get; set; }
        public int EjecutivoId { get; set; }
        public string Fecha { get; set; }
        public Nullable<int> EstatusId { get; set; }
    
        public virtual Ejecutivos Ejecutivos { get; set; }
        public virtual Estatus Estatus { get; set; }
    }
}
