//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Careers.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_historico
    {
        public int Id { get; set; }
        public string Ejecutivo { get; set; }
        public string Empresa { get; set; }
        public string Colaborador { get; set; }
        public string EmpresaColaborador { get; set; }
        public string Area { get; set; }
        public string Fecha { get; set; }
        public string Canal { get; set; }
        public string Estatus { get; set; }
    }
}
