//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Careers.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_perfil_ejecutivos
    {
        public int Id { get; set; }
        public string Ejecutivo { get; set; }
        public Nullable<int> Completado { get; set; }
    }
}
