//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Careers.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vacante
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public int EmpresaId { get; set; }
        public int CiudadId { get; set; }
        public int AreaId { get; set; }
        public int NivelOrganizacionalId { get; set; }
        public int TipoPublicacionId { get; set; }
        public string UrlDestino { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaFinalizacion { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual Ciudad Ciudad { get; set; }
        public virtual Empresa Empresa { get; set; }
        public virtual NivelOrganizacional NivelOrganizacional { get; set; }
        public virtual TipoPublicacion TipoPublicacion { get; set; }
    }
}
